In [1]:
import numpy as np

In [9]:
# 0-D Array

arr = np.array(4)
print(arr)
print(arr.ndim)

4
0


In [8]:
# 1-D Array

arr_01 = np.array([11,22,33,44,55])
print(arr_01)
print(arr_01.ndim)

[11 22 33 44 55]
1


In [10]:
# 2-D Array

arr_02 = np.array([[7,4,1], [8,5,2]])
print(arr_02)
print(arr_02.ndim)

[[7 4 1]
 [8 5 2]]
2


In [11]:
# 3-D Array
arr_03 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_03)
print(arr_03.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [20]:
# 5-D Array

arr_05 = np.array([1,2,3,4], ndmin=5)
print(arr_05)
print("number of dimension: ", arr_05.ndim)

[[[[[1 2 3 4]]]]]
number of dimension:  5
